# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/ip/RAM_c1_c2/RAM_c1_c2.xci
# IP: The module: 'RAM_c1_c2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/20212/AppData/Roaming/Xilinx/Vivado/users/lenovo/vivado/22.1/video_base_v2.0_ori/video_base_v2.0.tmp/aod_net_v1_1_project/AOD_Net_v1_1_project.gen/sources_1/ip/RAM_c1_c2/RAM_c1_c2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_c1_c2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/ip/RAM_c1_c2/RAM_c1_c2.xci
# IP: The module: 'RAM_c1_c2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/20212/AppData/Roaming/Xilinx/Vivado/users/lenovo/vivado/22.1/video_base_v2.0_ori/video_base_v2.0.tmp/aod_net_v1_1_project/AOD_Net_v1_1_project.gen/sources_1/ip/RAM_c1_c2/RAM_c1_c2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_c1_c2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
