# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/synth_1/AOD_Net_v1_1.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 8
set_param simulator.modelsimInstallPath D:/Modelsim/win64
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.cache/wt [current_project]
set_property parent.project_path D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs [current_project]
update_ip_catalog
set_property ip_output_repo d:/20212/user/vivado/22.1/AOD_Net/AOD_Net.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l9_synth_1/RAM_q2_l9.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l9_synth_1/RAM_q2_l9.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l8_synth_1/RAM_q2_l8.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l8_synth_1/RAM_q2_l8.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l7_synth_1/RAM_q2_l7.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l7_synth_1/RAM_q2_l7.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l6_synth_1/RAM_q2_l6.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l6_synth_1/RAM_q2_l6.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l5_synth_1/RAM_q2_l5.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l5_synth_1/RAM_q2_l5.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l4_synth_1/RAM_q2_l4.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l4_synth_1/RAM_q2_l4.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l3_synth_1/RAM_q2_l3.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l3_synth_1/RAM_q2_l3.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l2_synth_1/RAM_q2_l2.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l2_synth_1/RAM_q2_l2.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l1_synth_1/RAM_q2_l1.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q2_l1_synth_1/RAM_q2_l1.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l7_synth_1/RAM_c3_c4_l7.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l7_synth_1/RAM_c3_c4_l7.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l6_synth_1/RAM_c3_c4_l6.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l6_synth_1/RAM_c3_c4_l6.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l5_synth_1/RAM_c3_c4_l5.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l5_synth_1/RAM_c3_c4_l5.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l4_synth_1/RAM_c3_c4_l4.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l4_synth_1/RAM_c3_c4_l4.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l3_synth_1/RAM_c3_c4_l3.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l3_synth_1/RAM_c3_c4_l3.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l2_synth_1/RAM_c3_c4_l2.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l2_synth_1/RAM_c3_c4_l2.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l1_synth_1/RAM_c3_c4_l1.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c3_c4_l1_synth_1/RAM_c3_c4_l1.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q3_synth_1/RAM_q3.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q3_synth_1/RAM_q3.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c4_c5_synth_1/RAM_c4_c5.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c4_c5_synth_1/RAM_c4_c5.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l6_synth_1/RAM_q1_l6.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l6_synth_1/RAM_q1_l6.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l5_synth_1/RAM_q1_l5.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l5_synth_1/RAM_q1_l5.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l4_synth_1/RAM_q1_l4.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l4_synth_1/RAM_q1_l4.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l3_synth_1/RAM_q1_l3.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l3_synth_1/RAM_q1_l3.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l2_synth_1/RAM_q1_l2.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l2_synth_1/RAM_q1_l2.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l1_synth_1/RAM_q1_l1.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_q1_l1_synth_1/RAM_q1_l1.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l5_synth_1/RAM_c2_c3_l5.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l5_synth_1/RAM_c2_c3_l5.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l4_synth_1/RAM_c2_c3_l4.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l4_synth_1/RAM_c2_c3_l4.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l3_synth_1/RAM_c2_c3_l3.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l3_synth_1/RAM_c2_c3_l3.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l2_synth_1/RAM_c2_c3_l2.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l2_synth_1/RAM_c2_c3_l2.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l1_synth_1/RAM_c2_c3_l1.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c2_c3_l1_synth_1/RAM_c2_c3_l1.dcp]
add_files -quiet D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c1_c2_synth_1/RAM_c1_c2.dcp
set_property used_in_implementation false [get_files D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.runs/RAM_c1_c2_synth_1/RAM_c1_c2.dcp]
read_verilog -library xil_defaultlib {
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/AOD_Net.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/AOD_Net_v1_1_M00_AXIS.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/AOD_Net_v1_1_S00_AXIS.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3_quant_ram/Quantize_2_3.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3_quant_ram/Quantize_2_3_top.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_quant_ram/Quantize_3_4.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_quant_ram/Quantize_3_4_top.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5_quant_ram/Quantize_4_5.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5_quant_ram/Quantize_4_5_top.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/cnt_loop.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv1/conv1.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv2/conv2.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv2/conv2_PE.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv2/conv2_ReLU.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv2/conv2_Weights.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv2/conv2_bais.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv2_ram/conv2_ram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv2_ram/conv2_tpram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3/conv3.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3/conv3_PE_5x5.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3/conv3_ReLU.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3/conv3_Weights.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3/conv3_bias.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3_quant_ram/conv3_q_ram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3_quant_ram/conv3_q_tpram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3_ram/conv3_ram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3/conv3_rearrange.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv3_ram/conv3_tpram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4/conv4.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4/conv4_PE_7x7.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4/conv4_ReLU.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4/conv4_Weights.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4/conv4_bias.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_ram/conv4_fir.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_quant_ram/conv4_q_fir.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_quant_ram/conv4_q_ram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_quant_ram/conv4_q_tpram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_ram/conv4_ram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4/conv4_rearrange.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv4_ram/conv4_tpram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5/conv5.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5/conv5_PE_3x3.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5/conv5_ReLU.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5_ram/conv5_TPRAM.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5/conv5_Weights.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5/conv5_bias.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5_quant_ram/conv5_q_TPRAM.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5_quant_ram/conv5_q_ram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5_ram/conv5_ram.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/conv5/conv5_rearrange.v
  D:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/new/AOD_Net_v1_1.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top AOD_Net_v1_1 -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AOD_Net_v1_1.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AOD_Net_v1_1_utilization_synth.rpt -pb AOD_Net_v1_1_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
