# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/ip/RAM_c5_cal/RAM_c5_cal.xci
# IP: The module: 'RAM_c5_cal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/20212/user/vivado/22.1/AOD_Net/AOD_Net.gen/sources_1/ip/RAM_c5_cal/RAM_c5_cal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_c5_cal'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/20212/user/vivado/22.1/AOD_Net/AOD_Net.srcs/sources_1/ip/RAM_c5_cal/RAM_c5_cal.xci
# IP: The module: 'RAM_c5_cal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/20212/user/vivado/22.1/AOD_Net/AOD_Net.gen/sources_1/ip/RAM_c5_cal/RAM_c5_cal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_c5_cal'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
